### ISSUE TITLE
Global connection already exists. Call sql.close() first.

### ISSUE THREAD

**Issue by orihomie** [mlaanderson/database-js#24]
I have a test like:

```js

async myFunction() {
...
try {
		conn = new Connection(connStr); 
		statement = conn.prepareStatement(orderIdsQuery);

		do {
			results = await statement.query();
		}
		while ([undefined, null].includes(results));

		let randomIndex = getRandomInt(0, results.length - 1);
		let orderId = results[randomIndex].Id;
		let multiDrive = results[randomIndex].DriverAmount === 1;

		statement = conn.prepareStatement(orderPeopleQuery);

		do {
			results = await statement.query(orderId);
		}
		while ([undefined, null].includes(results));

		result = {'orderId': orderId, 'multiDrive': multiDrive, 'people': results};
	}
	catch (reason) {
		console.log(reason);
	}
	finally {
		if (conn) {
			await conn.close();
		}
	}

	return result;
}

Before() {
...
let res = await myFunction();
...
}

Scenario() {
...
}.retry(1)
```

It is expected that test to work like this:
If it fails - it starts again, completes request once more, and then goes to scenario steps, but 
I got this exception after test restarted:

```js
Error: Global connection already exists. Call sql.close() first.
    at Object.connect (/Users/orkhan.mamedov/WebstormProjects/SravniClient/node_modules/database-js-mssql/node_modules/mssql/lib/base.js:1639:10)
    at MsSql._pool (/Users/orkhan.mamedov/WebstormProjects/SravniClient/node_modules/database-js-mssql/index.js:61:33)
    at MsSql.query (/Users/orkhan.mamedov/WebstormProjects/SravniClient/node_modules/database-js-mssql/index.js:73:31)
    at /Users/orkhan.mamedov/WebstormProjects/SravniClient/node_modules/database-js/lib/statement.js:69:38
    at new Promise (<anonymous>)
    at PreparedStatement.query (/Users/orkhan.mamedov/WebstormProjects/SravniClient/node_modules/database-js/lib/statement.js:60:16)
...
```

It seems as a bug, can you help me with that?

**Comment by orihomie** [comment]
Okay, my issue was resolved in 

> database-js-mssql

But author didnt updated npm package so I've spent a day to find out whats wrong.

**Comment by mlaanderson** [comment]
I've worked with @thiagodp on the database-js and some of its drivers, but [database-js-mssql](https://github.com/thiagodp/database-js-mssql/issues) is all his project. I wasn't even aware it existed. I'm glad this is expanding beyond what I follow. 

In this case it's best to move the issue over to the driver repository.

**Comment by thiagodp** [comment]
Hi @orihomie, please feel free to open an Issue at [database-js-mssql](https://github.com/thiagodp/database-js-mssql/issues).

**Comment by thiagodp** [comment]
@orihomie [database-js-mssql](https://github.com/thiagodp/database-js-mssql/issues) `0.3` is now published. Thank you for letting us know.
